apiVersion: v1
kind: Service
metadata:
  name: sapan-portfolio-service
spec:
  type: LoadBalancer
  selector:
    app: sapan-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
